name: Publish Edge Client
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # - name: Run tests
      #   run: npm test
      
      - name: Build package
        run: npm run build
      
      - name: Check package.json
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found"
            exit 1
          fi
          
          # Check if package name exists
          if ! npm pkg get name > /dev/null 2>&1; then
            echo "Error: package name not found in package.json"
            exit 1
          fi
          
          # Check if version exists
          if ! npm pkg get version > /dev/null 2>&1; then
            echo "Error: package version not found in package.json"
            exit 1
          fi
      
      - name: Dry run publish
        run: npm publish --dry-run --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          